### ISSUE TITLE
I'd like to know what dataset you used.

### ISSUE THREAD

**Issue by Hobeom** [nasir6/face-segmentation#1]
You said, Data was obtained and merged from multiple resources.
May i ask where can i get resources

**Comment by nasir6** [comment]
- http://pages.cs.wisc.edu/~lizhang/projects/face-parsing/
- http://vis-www.cs.umass.edu/lfw/
- https://www.kaggle.com/jessicali9530/celeba-dataset

**Comment by JiaojiaoYe1994** [comment]
@HoBeom @nasir6  Hi guys, could you guys provide me some ideas for how to prepare these dataset and merge them to final dataset.
